<img src="https://raw.githubusercontent.com/practicalAI/images/master/images/02_Numpy/numpy.png" width="200" vspace="30px" align="right">

<div align="left">
<h1>NumPy</h1>

Dans cette leçon, nous allons apprendre les bases de l'analyse numérique avec le package NumPy.
</div>

# Set up

In [0]:
import numpy as np

# Les Bases

Voyons maintenant comment créer des Matrice avec NumPy.

*    **Matrice**: collection de valeurs 

<div align="left">
<img src="https://raw.githubusercontent.com/practicalAI/images/master/images/02_Numpy/tensors.png" width="550">
</div>

In [0]:
# Scalar
x = np.array(6) # scalar
print ("x: ", x)
# Number of dimensions
print ("x ndim: ", x.ndim)
# Dimensions
print ("x shape:", x.shape)
# Size of elements
print ("x size: ", x.size)
# Data type
print ("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [0]:
# Vector
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


In [0]:
# Matrix
x = np.array([[1,2], [3,4]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[1 2]
 [3 4]]
x ndim:  2
x shape: (2, 2)
x size:  4
x dtype:  int64


In [0]:
# Matrice 3D
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int64



NumPy est également livré avec plusieurs fonctions qui nous permettent de créer rapidement des matrices.

In [0]:
# Functions
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2))) # identity matrix 
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


# Indexation

Gardez à l'esprit que lors de l'indexation de la ligne et de la colonne, les index commencent à 0. Et comme pour l'indexation avec des listes, nous pouvons également utiliser des index négatifs (où -1 est le dernier élément).

<div align="left">
<img src="https://raw.githubusercontent.com/practicalAI/images/master/images/02_Numpy/indexing.png" width="250">
</div>

In [0]:
# Indexing
x = np.array([1, 2, 3])
print ("x: ", x)
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [0]:
# Slicing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1]) 
print ("x row 0: ", x[0, :]) 
print ("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [0]:
# Integer array indexing
print (x)
rows_to_get = np.array([0, 1, 2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
# Combine sequences above to get values to get
print ("indexed values: ", x[rows_to_get, cols_to_get]) # (0, 0), (1, 2), (2, 1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [0]:
# Boolean array indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)
print ("x[x > 2]:\n", x[x > 2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# Arithmetic


In [0]:
# Basic math
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


### Produit Scalaire

L’une des opérations NumPy les plus courantes que nous utiliserons en machine learning est la multiplication matricielle à l’aide du produit scalaire. Nous prenons les lignes de notre première matrice (2) et les colonnes de notre deuxième matrice (2) pour déterminer le produit scalaire, nous donnant un résultat de `[2 X 2]`. La seule exigence est que les dimensions intérieures correspondent, dans ce cas, la première matrice a 3 colonnes et la deuxième matrice a 3 lignes.

<div align="left">
<img src="https://raw.githubusercontent.com/practicalAI/images/master/images/02_Numpy/dot.gif" width="400">
</div>

In [0]:
# Produit scalaire
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
c = a.dot(b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print (c)

(2, 3) · (3, 2) = (2, 2)
[[ 58.  64.]
 [139. 154.]]


### Opérations sur les axes

Nous pouvons également effectuer des opérations sur un axe spécifique.

<div align="left">
<img src="https://raw.githubusercontent.com/practicalAI/images/master/images/02_Numpy/axis.gif" width="400">
</div>

In [0]:
# Sum across a dimension
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) # sum across columns

[[1 2]
 [3 4]]
sum all:  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


In [0]:
# Min/max
x = np.array([[1,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

min:  1
max:  6
min axis=0:  [1 2 3]
min axis=1:  [1 4]


### Broadcasting

Ici, nous ajoutons un vecteur avec un scalaire. Leurs dimensions ne sont pas compatibles telles quelles, mais comment NumPy nous donne-t-il toujours le bon résultat ? C’est là que le broadcasting entre en jeu. Le scalaire est *broadcast* sur le vecteur afin que leurs formes soient compatibles.

<div align="left">
<img src="https://raw.githubusercontent.com/practicalAI/images/master/images/02_Numpy/broadcasting.png" width="220">
</div>

In [0]:
# Broadcasting
x = np.array([1,2]) # vector
y = np.array(3) # scalar
z = x + y
print ("z:\n", z)

z:
 [4 5]


# Avancé

### Transposition

Nous avons souvent besoin de modifier les dimensions de nos matrices pour des opérations telles que le produit scalaire. Si nous devons permuter deux dimensions, nous pouvons transposer la matrices.

<div align="left">
<img src="https://raw.githubusercontent.com/practicalAI/images/master/images/02_Numpy/transpose.png" width="350">
</div>

In [0]:
# Transposing
x = np.array([[1,2,3], [4,5,6]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
print ("y:\n", y)
print ("y.shape: ", y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[1 4]
 [2 5]
 [3 6]]
y.shape:  (3, 2)


### Reshaping

Parfois, nous devons modifier les dimensions de la matrice. Le Reshaping nous permet de transformer une matrice en différentes formes permises - notre matrice remodelé a la même quantité de valeurs dans la matrice. (1X6 = 2X3). Nous pouvons également utiliser `-1` sur une dimension et NumPy déduira en fonction de notre matrice d'entrée.

La façon dont fonctionne le reshaping consiste à examiner chaque dimension de la nouvelle matrice et à séparer notre matrice d'origine en autant d'unités. Donc, ici, la dimension à l'indice 0 de la nouvelle matrice est 2, nous divisons donc notre matrice d'origine en 2 unités, chacune d'elles ayant 3 valeurs.

<div align="left">
<img src="https://raw.githubusercontent.com/practicalAI/images/master/images/02_Numpy/reshape.png" width="400">
</div>

In [0]:
# Reshaping
x = np.array([[1,2,3,4,5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y: \n", y)
print ("y.shape: ", y.shape)
z = np.reshape(x, (2, -1))
print ("z: \n", z)
print ("z.shape: ", z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


### Ajout / suppression de dimensions

Nous pouvons également facilement ajouter et supprimer des dimensions à nos matrices et nous voudrons le faire pour rendre les matrices compatibles pour certaines opérations.

In [0]:
# Adding dimensions
x = np.array([[1,2,3],[4,5,6]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.expand_dims(x, 1) # expand dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)   # notice extra set of brackets are added

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


In [0]:
# Removing dimensions
x = np.array([[[1,2,3]],[[4,5,6]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # squeeze dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)  # notice extra set of brackets are gone

x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


# Ressources supplémentaires

* **NumPy reference manual**: Si vous voulez en savoir plus : [NumPy reference manual](https://docs.scipy.org/doc/numpy-1.15.1/reference/).